[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "coconut-tools"
version = "1.1.0"
description = "Tools for COCONUT: 3D coronal analysis, input preparation, and coupling with heliospheric models such as EUHFORIA."
readme = "README.md"
requires-python = ">=3.10"
license = { text = "MIT" }
authors = [{ name = "Luis Linan" }]

dependencies = [
  "astropy",
  "beautifulsoup4",    # bs4
  "cmocean",
  "colorlog",
  "h5py",
  "imageio[ffmpeg]",
  "matplotlib",
  "natsort",
  "numpy",
  "opencv-python",
  "pandas",
  "pyevtk",
  "pyvista",
  "requests",
  "scipy",
  "scikit-learn",      # sklearn
  "solarmach",
  "sunpy",
  "tqdm",
  "vtk"
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
include = ["coconut_tools*"]

[project.optional-dependencies]
docs = [
  "sphinx>=7",
  "furo",
  "sphinx-autodoc-typehints",
  "sphinx-copybutton",
  "sphinx-design"
]

test = [
  "pytest",
]
