# pytest.ini
[pytest]
# Directories where pytest will search for tests
testpaths = tests

# Custom markers declaration
markers =
    bigdata: tests that require large external files

# Default options (optional, remove if you prefer to be explicit)
addopts = -v
